CREATE TYPE "ItemCategory" AS ENUM ('BOOK','NOTEBOOK','BACKPACK','PENCIL','PEN','ERASER','PENCIL_CASE','UNIFORM','SHOES','SCHOOL_SUPPLIES');
CREATE TYPE "ItemCondition" AS ENUM ('NEW','GOOD','FAIR');
CREATE TYPE "ItemAvailability" AS ENUM ('AVAILABLE','DONATED');
CREATE TYPE "UserType" AS ENUM ('ADMIN','DONOR','RECEIVER','INSTITUTION');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING','APPROVED','COMPLETED','CANCELED');
CREATE TABLE "user" ("id" TEXT PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "password" TEXT NOT NULL, "name" TEXT, "type" "UserType" NOT NULL DEFAULT 'DONOR', "phones" TEXT[] NOT NULL, "address" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "item" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE RESTRICT, "name" TEXT NOT NULL, "description" TEXT, "category" "ItemCategory" NOT NULL, "condition" "ItemCondition" NOT NULL, "availability" "ItemAvailability" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "order" ("id" TEXT PRIMARY KEY, "status" "OrderStatus" NOT NULL, "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE RESTRICT, "itemId" TEXT NOT NULL REFERENCES "item"("id") ON DELETE RESTRICT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "order_userId_itemId_key" UNIQUE("userId","itemId"));
